class JsonData:
    """Represents data pulled from the JSON files that are generated by unpacking the LBAL pack files."""


class SQLData:
    """Represents data pulled from the sqlite database generated by the wiki. This class will only be used for a
    reference based on the extracted data from the PAK files."""


class Symbol:
    """Class for the symbols"""
    def __init__(self, id, groups, rarity, value):
        self.id = id
        self.value = value
        self.groups = groups
        self.rarity = rarity

